#服务启动端口
server :  
  port :  16666

#数据库配置
spring:
    mvc:
        view:
            prefix: /
            suffix: .html
    resources:
        static-locations: classpath:static/
    datasource:
        name: test
        url: jdbc:mysql://47.106.177.128:3306/scyz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        #url: jdbc:mysql://localhost:3306/scyz?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true&useSSL=false&zeroDateTimeBehavior=convertToNull
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        
    http:
        multipart:
            maxFileSize: 50Mb  
            maxRequestSize: 50Mb 
    
mybatis:
  type-aliases-package: com.lensyn.gxpt.service.mapper
  mapper-locations: classpath:mapper/*.xml
  configLocation: classpath:mybatis-config.xml
    
# 日志输出
logging: 
    file: D:/boot.log
    level: 
        com.ibatis:DEBUG
        root:DEBUG

task:
    cron:0 0/5 * * * ?
       
    
